// Code generated by codegen.go; DO NOT EDIT.

package main

// Getters and setters for Person
func (s *Person) GetName() string {
    return s.Name
}

func (s *Person) SetName(value string) {
    s.Name = value
}

func (s *Person) GetAge() int {
    return s.Age
}

func (s *Person) SetAge(value int) {
    s.Age = value
}

func (s *Person) GetAddress() string {
    return s.Address
}

func (s *Person) SetAddress(value string) {
    s.Address = value
}

// Getters and setters for Company
func (s *Company) GetName() string {
    return s.Name
}

func (s *Company) SetName(value string) {
    s.Name = value
}

func (s *Company) GetLocation() string {
    return s.Location
}

func (s *Company) SetLocation(value string) {
    s.Location = value
}

func (s *Company) GetEmployees() int {
    return s.Employees
}

func (s *Company) SetEmployees(value int) {
    s.Employees = value
}

